#!/usr/bin/env python3
"""
Environment Setup Script for Labib Telegram Bot
This script helps you set up your environment variables
"""

import os
import shutil
from pathlib import Path

def setup_environment():
    """Set up environment variables for the bot"""
    
    print("🔧 Labib Telegram Bot Environment Setup")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    # Check if vision-ocr-key.json exists
    if not os.path.exists('vision-ocr-key.json'):
        print("❌ vision-ocr-key.json not found!")
        print("Please ensure your Google Cloud Vision credentials file is in the project root.")
        return
    
    # Create .env file
    env_content = """# Labib Telegram Bot Environment Variables
# Generated by setup_env.py

# Telegram Bot Configuration
TELEGRAM_TOKEN=your_telegram_bot_token_here

# OpenAI Configuration
OPENAI_API_KEY=your_openai_api_key_here

# Google Cloud Vision Configuration
GOOGLE_APPLICATION_CREDENTIALS=./vision-ocr-key.json
GOOGLE_CLOUD_PROJECT_ID=our-highway-326316

# Instagram Configuration (Optional - for future use)
IG_USER_ID=your_instagram_user_id_here
IG_ACCESS_TOKEN=your_instagram_access_token_here

# Database Configuration
CHROMA_DB_PATH=./chroma_store

# Application Configuration
LOG_LEVEL=INFO
ENVIRONMENT=development
"""
    
    try:
        with open('.env', 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        print("✅ .env file created successfully!")
        print("\n📝 Next steps:")
        print("1. Edit .env file and add your actual API keys:")
        print("   - TELEGRAM_TOKEN: Get from @BotFather on Telegram")
        print("   - OPENAI_API_KEY: Get from OpenAI dashboard")
        print("2. Run the bot with: python telegram_bot.py")
        print("3. Or use Docker: docker-compose up")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

def check_requirements():
    """Check if required files exist"""
    print("\n🔍 Checking requirements...")
    
    required_files = [
        'vision-ocr-key.json',
        'telegram_bot.py',
        'requirements.txt'
    ]
    
    missing_files = []
    for file in required_files:
        if os.path.exists(file):
            print(f"✅ {file}")
        else:
            print(f"❌ {file}")
            missing_files.append(file)
    
    if missing_files:
        print(f"\n⚠️  Missing files: {', '.join(missing_files)}")
        print("Please ensure all required files are present.")
    else:
        print("\n✅ All required files are present!")

if __name__ == "__main__":
    setup_environment()
    check_requirements()
